### PR TITLE
Fixed icons on smaller viewports

### LINKED ISSUE #214: bug: sound list icons are broken on smaller viewports
## How to Reproduce
1. Open DevTool.
2. Switch to smaller viewport. 
3. Icons will look wonky.

## Expected
Icons remain same size regardless of viewport.

### PR DESCRIPTION
**Pull request by akshara-sun**
fixes #214

### CODE REVIEW

**Review by hamirmahal — CHANGES_REQUESTED** [review]
I think things look okay until we get to about the 2/3 mark on a 1366 x 768 pixel screen, but below that, icons lose alignment and shrink. 

Screen Shot 2020-12-16 at 10 37 26 AM

Screen Shot 2020-12-16 at 10 37 51 AM

**Comment by akshara-sun** [comment]
> I think things look okay until we get to about the 2/3 mark on a 1366 x 768 pixel screen, but below that, icons lose alignment and shrink.
> 
> Screen Shot 2020-12-16 at 10 37 26 AM
> 
> Screen Shot 2020-12-16 at 10 37 51 AM

Gotcha - I am working on that right now.

**Comment by akshara-sun** [comment]
Heads Up @amilajack @hamirmahal :
When I formatted these icons a while back, I added padding to make sure they were aligned but I figured out how to remove that and use flexbox so now the code is a lot simpler. I will be pushing changes soon so you can take a look then :)

**Comment by akshara-sun** [comment]
> Heads Up @amilajack @hamirmahal :
> When I formatted these icons a while back, I added padding to make sure they were aligned but I figured out how to remove that and use flexbox for the alignment so now the code is a lot simpler! I will be pushing changes soon so you can take a look then 😊

Yo this was the solution to the alignment problem 😂

**Comment by amilajack** [comment]
Seems like another issue breaks the icons. We'll have to truncate long sound names:

https://tide-ni68eeirb.vercel.app/search?q=chant

Screen Shot 2020-12-16 at 10 57 37 AM

**Comment by amilajack** [comment]
Was already broken on master. We should create a separate PR for this

Screen Shot 2020-12-16 at 11 11 30 AM

**Pull request merged**
